apiVersion: v1
kind: ConfigMap
metadata:
  name: gin-template
  namespace: apps
data:
  config.toml: |
    [general]
    # Log level
    # trace=6, debug=5, info=4, warning=3, error=2, fatal=1, panic=0
    log_level=4
    log_format="text"
    enable_db=true
    enable_kv_db=false
    enable_leader_election=false

    [api]
    # ip:port to bind the api server
    addr="0.0.0.0:8080"
    # ip:port to bind the api server which enable tls
    tls_addr=""
    # tls crt and key
    tls_crt=""
    tls_key=""

    [db]
    # db connection info
    type="sqlite"
    dsn="/var/lib/gin-template/sqlite.db"
    min_idle_conns=100
    max_active_conns=200
    conn_lifetime="1h0m0s"
    conn_idletime="30m0s"

    [kv_db]
    # kv_db connection info
    type="redis"
    dsn="redis://127.0.0.1:6379"
    min_idle_conns=100
    max_active_conns=200
    conn_lifetime="1h0m0s"
    conn_idletime="30m0s"