apiVersion: v1
kind: Service
metadata:
  name: gin-template
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: gin-template
  ports:
    - name: web
      port: 8080
      targetPort: 8080